# Generated by Django 3.2.4 on 2021-08-21 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.UUIDField(default=uuid.uuid4, help_text='Example: c8daa3ac-3dd0-44e9-ba2a-b0cbd1c8d8ae.', primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=1000)),
                ('sent_at', models.DateTimeField(default=datetime.datetime(2021, 8, 21, 14, 50, 10, 231687, tzinfo=utc))),
                ('messeger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('roomId', models.UUIDField(default=uuid.uuid4, help_text='Example: c8daa3ac-3dd0-44e9-ba2a-b0cbd1c8d8ae.', primary_key=True, serialize=False, unique=True)),
                ('roomName', models.CharField(max_length=500)),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='blogapp.profile')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='blogapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('messageReactionId', models.UUIDField(default=uuid.uuid4, help_text='Example: c8daa3ac-3dd0-44e9-ba2a-b0cbd1c8d8ae.', primary_key=True, serialize=False, unique=True)),
                ('reaction', models.BooleanField(default=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.message')),
                ('reactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.messageroom'),
        ),
    ]
