# Generated by Django 3.2.4 on 2021-08-23 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_message_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 15, 14, 15, 955848, tzinfo=utc)),
        ),
    ]
